### ISSUE TITLE
Collapse containers on mobile

### ISSUE THREAD

**Issue by bryanp** [pakyow/css#5]
We always end up doing this:

```css
*[class*="container"] {
  @include mobile {
    width: 100% !important;

    .col {
      width: 100% !important;
      margin-left: 0;
      margin-right: 0;
    }
  }
}
```
